### ISSUE TITLE
Can't seem to upgrade from 2.4.0 to 3.0.0

### ISSUE THREAD

**Issue by rstudner** [Exelord/ember-initials#22]
Do a full nombom/the works.  Whenever I try to startup with 3.0.0 I get this:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/rstudner/projects/expel-ember/tmp/source_map_concat-input_base_path-Nbe3DzZZ.tmp/bower_components/blueimp-md5/js/md5.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/rstudner/projects/expel-ember/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/rstudner/projects/expel-ember/node_modules/broccoli-concat/concat.js:134:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/rstudner/projects/expel-ember/node_modules/broccoli-concat/concat.js:132:24)
    at /Users/rstudner/projects/expel-ember/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/rstudner/projects/expel-ember/node_modules/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise (/Users/rstudner/projects/expel-ember/node_modules/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1077:31)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/Users/rstudner/projects/expel-ember/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/Users/rstudner/projects/expel-ember/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/Users/rstudner/projects/expel-ember/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:392:10)
    at EmberApp._concatFiles (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:405:15)
    at EmberApp.javascript (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1297:12)
    at EmberApp.toArray (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
    at module.exports (/Users/rstudner/projects/expel-ember/ember-cli-build.js:60:14)
    at CoreObject.setupBroccoliBuilder (/Users/rstudner/projects/expel-ember/node_modules/ember-cli/lib/models/builder.js:84:19)
```

**Comment by Exelord** [comment]
OK, I released v3.0.1 and checked it on my project. Could you confirm if the issue is resolved for you?

**Comment by alechirsch** [comment]
@Exelord +1 I get the same exact error on 3.0.1

**Comment by Exelord** [comment]
@alechirsch v3.0.3 - just run `ember install ember-initials` one more time to install md5 dependency

**Comment by alechirsch** [comment]
@Exelord I hate to say it but I am still getting the same error

```
Error: ENOENT: no such file or directory, stat '/Users/alechirsch/Documents/projects/project-app/tmp/source_map_concat-input_base_path-oFFHOItX.tmp/0/undefined/blueimp-md5/js/md5.min.js'
```

**Comment by alechirsch** [comment]
It looks like there is an `undefined` variable where bower_components is supposed to be

**Comment by Exelord** [comment]
Could you try to manually change version in packages to 3.0.3 and then use
install command?

**Comment by alechirsch** [comment]
@Exelord Same problem, there is an undefined in the path where bower_components should be.

**Comment by Exelord** [comment]
If you upgrading from 3.0.0 and up to 3.0.3 please run `ember generate ember-initials` it should solve the problem with bower dependency or remove completely ember-initials from package.json and run `ember install ember-initials`
