### ISSUE TITLE
Cannot read property 'initialsFor' of undefined

### ISSUE THREAD

**Issue by stephanebruckert** [Exelord/ember-initials#46]
Using `"ember-initials": "~3.6.0"` and `"ember-cli": "2.17.1"`:

```
TypeError: Cannot read property 'initialsFor' of undefined
    at Class.createInitials (http://localhost:4200/assets/addon-tree-output/ember-initials/mixins/initials.js:62:1)
    at Class.<anonymous> (http://localhost:4200/assets/addon-tree-output/ember-initials/mixins/initials.js:28:1)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/ember-metal.js:3494:1)
    at get (http://localhost:4200/assets/ember-metal.js:2836:1)
    at RootPropertyReference.compute (http://localhost:4200/assets/ember-glimmer/utils/references.js:191:1)
    at RootPropertyReference.value (http://localhost:4200/assets/ember-glimmer/utils/references.js:58:1)
    at ReferenceCache.initialize (http://localhost:4200/assets/@glimmer/reference.js:395:1)
    at ReferenceCache.peek (http://localhost:4200/assets/@glimmer/reference.js:369:1)
    at DynamicAttribute.flush (http://localhost:4200/assets/@glimmer/runtime.js:1486:1)
    at ComponentElementOperations.flush (http://localhost:4200/assets/@glimmer/runtime.js:1312:1)
```

```
  createInitials() {
    return this.get('avatarsStore').initialsFor(this.initialsProperties());
  },
```
https://github.com/Exelord/ember-initials/blob/master/addon/mixins/initials.js#L73

3.5.0 is OK

**Comment by Exelord** [comment]
Hmm, I upgraded the demo to 2.18 and there is no error. Are u using fastboot-app-server? Could you try with the latest master?

**Comment by stephanebruckert** [comment]
Maybe it's worth me saying that it only happens in my test (it was passing < 3.6.0) which is probably wrong now. I've just added `this.inject.service('store');` but it still fails. Maybe you've got an idea?

```
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

moduleForComponent('authenticated-navbar', 'Integration | Component | authenticated navbar', {
  integration: true,
  beforeEach: function() {
    this.inject.service('store');
  }
});

test('it renders', function(assert) {
  let currentUser = { fullname: 'John' };
  this.set('currentUser', currentUser);
  this.render(hbs`{{authenticated-navbar currentUser=currentUser}}`);
  assert.ok(this.$('.dropdown a img[src^="blob"]').length == 1, 'it has a blank initials picture');
  assert.equal(this.$('.dropdown a img').attr('width'), '32', 'it has an avatar picture');
  assert.equal(this.$('input[placeholder="Search"]').length, 1, 'it has a search box');
  assert.equal(this.$('a[href^="https://www.elsevier.com/solutions/hivebench/learn-and-support"]').length, 1, 'it has a link to help pages');
});
```

```
import Ember from 'ember';

const { Component, inject: { service } } = Ember;

export default Component.extend({
  currentUser: service('currentUser'),
  authManager: service('user'),

  didInsertElement() {
    this.$('[data-toggle="tooltip"]').tooltip();
  },

  actions: {
    invalidateSession() {
      this.get('authManager').invalidate();
    }
  }
});
```

```
{{ember-initials image=currentUser.avatar
                             name=currentUser.username
                             size=32}}
```

**Comment by Exelord** [comment]
Oh, yeah.. that's because initializers are not executed in integration tests :/ Ok, I see the new container brings more issues than improvements. I will do a new release for a while.

**Comment by stephanebruckert** [comment]
Ok I will use 3.5.0 for now. Thank you!

**Comment by Exelord** [comment]
@stephanebruckert Please check out v3.6.1 :) I hope it will fix your problem now

**Comment by stephanebruckert** [comment]
Thanks for the revert! Back to `^`

**Comment by Exelord** [comment]
It wasn't a revert. I just rework it a little :)
